apiVersion: v2
name: jimbe
description: A Helm chart for jimbe
type: application
keywords:
  - jimbe
  - api
home: https://github.com/w6d-io/jimbe
sources:
  - https://github.com/w6d-io/jimbe
maintainers:
  - name: WILDCARD
    url: https://w6d.io
icon: https://w6d.io/favicon.ico
appVersion: v2.0.0
version: 0.3.8
