apiVersion: v2
name: app
version: 1.2.0
appVersion: v1.0.1
description: 'Chart Created by David ALEXANDRE <david.alexandre@w6d.io>'
keywords:
  - app
home: https://www.w6d.io
sources:
  - https://charts.w6d.io
maintainers:
  - name: Wildcard
    email: support@w6d.io
  - name: david972
    email: david.alexandre@w6d.io
icon: https://gitlab.w6d.io/favicon.ico
