{{- if and .Values.oathkeeper.enabled .Values.oathkeeper.accessRules }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth.accessRules.configMapName" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: oathkeeper
data:
  access-rules.json: |
    {{- .Values.oathkeeper.accessRules | nindent 4 }}
{{- end }}
