{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kratos-login-ui.serviceAccountName" . }}
  labels:
    {{- include "kratos-login-ui.labels" . | nindent 4 }}
{{- end }}
