{{- if .Values.webhook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth.webhook.fullname" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      {{- include "auth.webhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "auth.webhook.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/webhook/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: kratos-webhook
          image: "{{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag }}"
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          command: ["/kratos-webhook", "serve"]
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 8081
          env:
            - name: LOG_LEVEL
              value: {{ .Values.webhook.logLevel | quote }}
            - name: CONFIG
              value: "/etc/kw/config.yaml"
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 0
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health/alive
              port: 8080
            initialDelaySeconds: 0
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - name: config
              mountPath: /etc/kw
      volumes:
        - name: config
          configMap:
            name: {{ include "auth.webhook.configMapName" . }}
{{- end }}
