{{- if .Values.opalStatic.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: opal-static
  labels:
    {{- include "auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: opal-static
spec:
  type: {{ .Values.opalStatic.service.type }}
  ports:
    - name: http
      port: {{ .Values.opalStatic.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "auth.opalStatic.selectorLabels" . | nindent 4 }}
{{- end }}
