{{- if .Values.kratos.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kratos.deployment.serviceAccount.name | default "kratos" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: kratos
  {{- with .Values.kratos.deployment.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
